all:
  hosts:
    inetRouter:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/centralRouter/virtualbox/private_key
    office1Router:
      ansible_host: 192.168.56.20
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/office1Router/virtualbox/private_key
    testClient1:
      ansible_host: 192.168.56.21
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/testClient1/virtualbox/private_key
    testServer1:
      ansible_host: 192.168.56.22
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/testServer1/virtualbox/private_key
    testClient2:
      ansible_host: 192.168.56.31
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/testClient2/virtualbox/private_key
    testServer2:
      ansible_host: 192.168.56.32
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./.vagrant/machines/testServer2/virtualbox/private_key
bondedservers:
  hosts:
    inetRouter:
      bond_ip: 192.168.255.1
    centralRouter:
      bond_ip: 192.168.255.2
clientservervlans:
  hosts:
    testClient1:
      vlan_id: 1
      vlan_ip: 10.10.10.254
    testServer1:
      vlan_id: 1
      vlan_ip: 10.10.10.1
    testClient2:
      vlan_id: 2
      vlan_ip: 10.10.10.254
    testServer2:
      vlan_id: 2
      vlan_ip: 10.10.10.1