---
- name: setup ifcfg-bond0
  become: yes
  ansible.builtin.template:
    src: ifcfg-bond0.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-bond0
    owner: root
    group: root
    mode: 0644
- name: setup interfaces
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/sysconfig/network-scripts/
    owner: root
    group: root
    mode: 0644
  with_items:
    - ifcfg-eth1
    - ifcfg-eth2
- name: reboot hosts for bond0
  become: yes
  reboot:
    reboot_timeout: 3600